#!/bin/bash

if [ ! -f ../.env ];then
	echo "please spacify .env file."
	exit 255
fi

. ../.env 

if [ ! -f ../.password ]; then
	echo "cannot read ../.password"
	exit 254
fi

. ../.password


cat << EOF > .env
DOMAIN_NAME=${DOMAIN_NAME}

LDAP_ORGANISATION=${LDAP_ORGANISATION}
LDAP_DOMAIN=${LDAP_DOMAIN}
LDAP_BASE_DN=${LDAP_BASE_DN}
LDAP_ADMIN_PASSWORD=${LDAP_ADMIN_PASSWORD}
LDAP_READONLY_USER_PASSWORD=${LDAP_READONLY_USER_PASSWORD}
LAM_PASSWORD=${LAM_PASSWORD}

MINIO_ROOT_USER=${MINIO_ROOT_USER}
MINIO_ROOT_PASSWORD=${MINIO_ROOT_PASSWORD}

KEYCLOAK_DB_USERNAME=${KEYCLOAK_DB_USERNAME}
KEYCLOAK_DB_PASSWORD=${KEYCLOAK_DB_PASSWORD}
KEYCLOAK_ADMIN=${KEYCLOAK_ADMIN}
KEYCLOAK_ADMIN_PASSWORD=${KEYCLOAK_ADMIN_PASSWORD}

SPARK_CATALOG_NAME=${SPARK_CATALOG_NAME}
SPARK_DB_NAME=${SPARK_DB_NAME}
SPARK_DB_USERNAME=${SPARK_DB_NAME}
SPARK_DB_PASSWORD=${SPARK_DB_PASSWORD}
EOF


COMPOSE_BAKE=true docker compose up -d --build

exit 0;
