services:
  keycloak:
    container_name: keycloak
    hostname: keycloak
    image: quay.io/keycloak/keycloak:latest
    environment:
      - TZ=Asia/Tokyo
      - KC_DB=postgres
      - KC_DB_URL_HOST=keycloak-db
      - KC_DB_URL_PORT=5432
      - KC_DB_USERNAME=keycloak
      - KC_DB_PASSWORD=${POSTGRES_PASSWORD}
      - KC_HOSTNAME=https://${DOMAIN_NAME}:8443
      - KEYCLOAK_ADMIN=${KEYCLOAK_ADMIN}
      - KEYCLOAK_ADMIN_PASSWORD=${KEYCLOAK_ADMIN_PASSWORD}
      - KC_HTTPS_CERTIFICATE_FILE=/opt/certs/${DOMAIN_NAME}.crt
      - KC_HTTPS_CERTIFICATE_KEY_FILE=/opt/certs/${DOMAIN_NAME}.key
    command:
      start
    restart: always
    ports:
      - 8443:8443
    volumes:
      - keycloak-volume:/opt/keycloak/data
      - ./kc.sh:/opt/keycloak/bin/kc.sh
      - ../certs/${DOMAIN_NAME}.ca.crt:/opt/certs/${DOMAIN_NAME}.ca.crt:ro
      - ../certs/${DOMAIN_NAME}.crt:/opt/certs/${DOMAIN_NAME}.crt:ro
      - ../certs/${DOMAIN_NAME}.key:/opt/certs/${DOMAIN_NAME}.key:ro
    tty: true
    user: root
    networks:
      keycloak-network:
        ipv4_address: 172.20.2.101
    depends_on:
      - keycloak-db

  keycloak-db:
    container_name: keycloak-db
    hostname: keycloak-db
    image: postgres:latest
    volumes:
      - keycloak-db-store:/var/lib/postgresql/data
    environment:
      - TZ=Asia/Tokyo
      - POSTGRES_USER=keycloak
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    networks:
      keycloak-network:
        ipv4_address: 172.20.2.102
    restart: always

volumes:
  keycloak-volume:
  keycloak-db-store:
networks:
  keycloak-network:
    driver: bridge
    ipam:
      driver: default
      config:
      - subnet: 172.20.2.0/24
        gateway: 172.20.2.1
