services:
  ldap-nginx:
    container_name: ldap-nginx
    hostname: ldap-nginx
    image: nginx:stable-alpine3.19-perl
    volumes:
      - ./conf/nginx.conf:/etc/nginx/nginx.conf
      - ../certs/${DOMAIN_NAME}.crt:/opt/certs/${DOMAIN_NAME}.crt:ro
      - ../certs/${DOMAIN_NAME}.key:/opt/certs/${DOMAIN_NAME}.key:ro
    ports:
      - 8085:80
      - 8444:443
    networks:
      ldap-network:
        ipv4_address: 172.20.1.100
  ldap:
    container_name: ldap
    hostname: ldap
    image: osixia/openldap:1.5.0
    ports:
      - 389:389
      - 636:636
    environment:
      - LDAP_ORGANISATION=${LDAP_ORGANISATION}
      - LDAP_DOMAIN=${LDAP_DOMAIN}
      - LDAP_ADMIN_PASSWORD=${LDAP_ADMIN_PASSWORD}
      - LDAP_BASE_DN=${LDAP_BASE_DN}
      - LDAP_READONLY_USER=true
      - LDAP_READONLY_USER_USERNAME=readonly
      - LDAP_READONLY_USER_PASSWORD=${LDAP_READONLY_USER_PASSWORD}
      - LDAP_TLS_VERIFY_CLIENT=never
      - LDAP_TLS_CRT_FILENAME=${DOMAIN_NAME}.crt
      - LDAP_TLS_KEY_FILENAME=${DOMAIN_NAME}.key
      - LDAP_TLS_CA_CRT_FILENAME=${DOMAIN_NAME}.ca.crt
      - TZ=Asia/Tokyo
    volumes:
      - ldap-data:/var/lib/ldap
      - ldap-config:/etc/ldap/slapd.d
      - ../certs/${DOMAIN_NAME}.ca.crt:/container/run/service/slapd/assets/certs/${DOMAIN_NAME}.ca.crt
      - ../certs/${DOMAIN_NAME}.crt:/container/run/service/slapd/assets/certs/${DOMAIN_NAME}.crt
      - ../certs/${DOMAIN_NAME}.key:/container/run/service/slapd/assets/certs/${DOMAIN_NAME}.key
    tty: true
    networks:
      ldap-network:
        ipv4_address: 172.20.1.101
    restart: always
  lam:
    container_name: lam
    hostname: lam
    image: ghcr.io/ldapaccountmanager/lam:stable
    environment: 
      - LDAP_DOMAIN=parallelcomputing.jp
      - LDAP_BASE_DN=dc=parallelcomputing,dc=jp
      - LDAP_USERS_DN=ou=people,dc=parallelcomputing,dc=jp
      - LDAP_GROUPS_DN=ou=groups,dc=parallelcomputing,dc=jp
      - LDAP_SERVER=ldap://ldap:389
      - LAM_LANG=ja_JP
      - LAM_PASSWORD=${LAM_PASSWORD}
      - VIRTUAL_HOST=lam
    networks:
      ldap-network:
        ipv4_address: 172.20.1.102

networks:
  ldap-network:
    driver: bridge
    ipam:
      driver: default
      config:
      - subnet: 172.20.1.0/24
        gateway: 172.20.1.1
volumes:
  ldap-data:
  ldap-config:
