services:
  pgsql:
    image: postgres:latest
    container_name: pgsql
    hostname: gpsql
    ports:
      - 5432:5432
    networks:
      pgsql-network:
        ipv4_address: 172.20.5.101
    volumes:
      - pgsql-store:/var/lib/postgresql/data
    tty: true
    restart: always
    environment:
      - TZ=Asia/Tokyo
      - POSTGRES_USER=${SPARK_DB_USERNAME}
      - POSTGRES_PASSWORD=${SPARK_DB_PASSWORD}
      - POSTGRES_DB=${SPARK_DB_NAME}

  adminer-nginx:
    container_name: adminer-nginx
    hostname: adminer-nginx
    image: nginx:stable-alpine3.19-perl
    volumes:
      - ./conf/nginx.conf:/etc/nginx/nginx.conf
      - ../certs/${DOMAIN_NAME}.crt:/opt/certs/${DOMAIN_NAME}.crt:ro
      - ../certs/${DOMAIN_NAME}.key:/opt/certs/${DOMAIN_NAME}.key:ro
    ports:
      - 8445:443
    networks:
      pgsql-network:
        ipv4_address: 172.20.5.100
        
  adminer:
    container_name: adminer
    hostname: adminer
    image: adminer
    restart: always
    networks:
      pgsql-network:
        ipv4_address: 172.20.5.102

networks:
  pgsql-network:
    driver: bridge
    ipam:
      driver: default
      config:
      - subnet: 172.20.5.0/24
        gateway: 172.20.5.1
volumes:
  pgsql-store:
